USE Northwind
GO
--1
CREATE TRIGGER CheckCustomerOnInsert ON Customers
FOR INSERT
AS
	BEGIN
		IF EXISTS(SELECT * FROM Customers WHERE Phone = NULL)
		BEGIN
			PRINT 'Khong duoc chen NULL'
			ROLLBACK TRANSACTION
		END
	END
GO
--2
CREATE TRIGGER CHECK_CUSTOMER_COUNTRY_ON_UPDATE
ON CUSTOMERS
FOR UPDATE
AS
	BEGIN
		IF EXISTS ( SELECT * FROM DELETED WHERE COUNTRY = 'FRANCE')
			BEGIN
			PRINT 'KHONG DUOC UPDATE'
			ROLLBACK TRAN
			END
	END
GO
DROP TRIGGER CHECK_CUSTOMER_COUNTRY_ON_UPDATE
GO
-- 3
ALTER TABLE CUSTOMERS
ADD Active int default(1)
GO
UPDATE CUSTOMERS
SET [Active] = 1
GO
SELECT * FROM Customers
GO
CREATE TRIGGER CHECK_CUSTOMER_INSTEADED_OF_DELETE
ON CUSTOMERS
FOR DELETE
AS
BEGIN
	UPDATE CUSTOMERS SET Active = 0 where CustomerID IN (SELECT CustomerID FROM deleted)
	ROLLBACK TRAN
END
GO
--4
sp_settriggerorder @triggername= 'CHECK_CUSTOMER_INSTEADED_OF_DELETE', @order='First', @stmttype = 'DELETE'
GO
--5
CREATE TRIGGER Safety
ON DATABASE
FOR CREATE_TABLE, DROP_TABLE, ALTER_TABLE
AS
BEGIN
PRINT'Need Permission'
ROLLBACK TRAN
END
GO
--6
DROP TRIGGER CheckCustomerOnInsert
DROP TRIGGER CHECK_CUSTOMER_COUNTRY_ON_UPDATE
DROP TRIGGER CHECK_CUSTOMER_INSTEADED_OF_DELETE